// examples/vue-chat-example.vue
<template>
  <div class="chat-app">
    <h1>Vue Chat with Transformers.js</h1>
    
    <!-- Status -->
    <div class="status-card" :class="{ ready: isReady, loading: isLoading }">
      <div v-if="isLoading">
        <strong>Ładowanie modelu...</strong>
        <div v-if="progress">
          {{ progress.file }}: {{ progress.progress }}%
        </div>
      </div>
      <div v-else-if="isReady">
        <strong>Model ready</strong>
      </div>
      <div v-if="providerError" class="error">
        Error: {{ providerError.message }}
      </div>
    </div>

    <!-- Messages -->
    <div class="messages-container" ref="messagesContainer">
      <div
        v-for="(msg, idx) in messages"
        :key="idx"
        class="message"
        :class="msg.role"
      >
        <div class="message-content">
          <em v-if="msg.role === 'system'">System: {{ msg.content }}</em>
          <template v-else>{{ msg.content }}</template>
        </div>
      </div>
      <div v-if="isSending" class="loading-message">
        Generowanie odpowiedzi...
      </div>
    </div>

    <!-- Input -->
    <div class="input-container">
      <input
        v-model="input"
        @keypress.enter="handleSend"
        placeholder="Napisz wiadomość..."
        :disabled="!isReady || isSending"
        class="message-input"
      />
      <button
        @click="handleSend"
        :disabled="!isReady || isSending || !input.trim()"
        class="send-button"
      >
        Wyślij
      </button>
      <button
        @click="clear"
        :disabled="messages.length === 0"
        class="clear-button"
      >
        Wyczyść
      </button>
    </div>

    <div v-if="chatError" class="error-message">
      Błąd: {{ chatError.message }}
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, watch, nextTick } from 'vue';
import { useAIProvider, useChat } from 'transformers-router/vue';

// Initialize AI Provider
const {
  provider,
  isReady,
  isLoading,
  progress,
  error: providerError,
} = useAIProvider({
  llm: {
    model: 'onnx-community/Qwen2.5-0.5B-Instruct',
    dtype: 'q4',
  },
  autoLoad: true,
});

// Initialize Chat
const {
  messages,
  isLoading: isSending,
  error: chatError,
  send,
  clear,
} = useChat(provider, {
  initialMessages: [
    {
      role: 'system',
      content: 'Jesteś pomocnym asystentem AI.',
    },
  ],
});

const input = ref('');
const messagesContainer = ref<HTMLElement>();

// Handle send message
const handleSend = async () => {
  if (!input.value.trim()) return;
  
  await send(input.value);
  input.value = '';
  
  // Scroll to bottom
  await nextTick();
  if (messagesContainer.value) {
    messagesContainer.value.scrollTop = messagesContainer.value.scrollHeight;
  }
};

// Auto-scroll on new messages
watch(messages, async () => {
  await nextTick();
  if (messagesContainer.value) {
    messagesContainer.value.scrollTop = messagesContainer.value.scrollHeight;
  }
}, { deep: true });
</script>

<style scoped>
.chat-app {
  max-width: 800px;
  margin: 0 auto;
  padding: 20px;
}

h1 {
  text-align: center;
  color: #333;
  margin-bottom: 20px;
}

.status-card {
  padding: 15px;
  margin-bottom: 20px;
  border-radius: 10px;
  background: #fff3cd;
}

.status-card.ready {
  background: #d4edda;
}

.status-card.loading {
  background: #cce5ff;
}

.messages-container {
  height: 400px;
  overflow-y: auto;
  padding: 20px;
  background: #f5f5f5;
  border-radius: 10px;
  margin-bottom: 20px;
}

.message {
  display: flex;
  margin-bottom: 10px;
}

.message.user {
  justify-content: flex-end;
}

.message.assistant,
.message.system {
  justify-content: flex-start;
}

.message-content {
  max-width: 70%;
  padding: 10px 15px;
  border-radius: 15px;
  box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
}

.message.user .message-content {
  background: #667eea;
  color: #fff;
}

.message.assistant .message-content,
.message.system .message-content {
  background: #fff;
  color: #333;
}

.loading-message {
  text-align: center;
  color: #666;
  font-style: italic;
}

.input-container {
  display: flex;
  gap: 10px;
}

.message-input {
  flex: 1;
  padding: 12px;
  font-size: 16px;
  border: 2px solid #e0e0e0;
  border-radius: 10px;
}

.message-input:disabled {
  background: #f5f5f5;
  cursor: not-allowed;
}

.send-button,
.clear-button {
  padding: 12px 24px;
  font-size: 16px;
  border: none;
  border-radius: 10px;
  cursor: pointer;
  color: #fff;
}

.send-button {
  background: #667eea;
}

.clear-button {
  background: #6c757d;
}

.send-button:disabled,
.clear-button:disabled {
  opacity: 0.6;
  cursor: not-allowed;
}

.error-message,
.error {
  margin-top: 10px;
  padding: 10px;
  background: #f8d7da;
  color: #721c24;
  border-radius: 5px;
}
</style>

// examples/react-chat-example.tsx
/**
 * React Chat Example with Transformers Router
 * 
 * To use this example:
 * 1. Install dependencies: npm install react react-dom @types/react @types/react-dom
 * 2. Add to your React app
 */

import React, { useEffect } from 'react';
import { useAIProvider, useChat } from 'transformers-router/react';

export function ChatApp() {
  const {
    provider,
    isReady,
    isLoading,
    progress,
    error: providerError,
    warmup,
  } = useAIProvider({
    llm: {
      model: 'onnx-community/Qwen2.5-0.5B-Instruct',
      dtype: 'q4',
    },
    autoLoad: true, // Auto-load model on mount
  });

  const {
    messages,
    isLoading: isSending,
    error: chatError,
    send,
    clear,
  } = useChat(provider, {
    initialMessages: [
      {
        role: 'system',
        content: 'Jesteś pomocnym asystentem AI.',
      },
    ],
  });

  const [input, setInput] = React.useState('');

  const handleSend = async () => {
    if (!input.trim()) return;
    
    await send(input);
    setInput('');
  };

  const handleKeyPress = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  };

  return (
    <div style={{ maxWidth: '800px', margin: '0 auto', padding: '20px' }}>
      <h1>React Chat with Transformers.js</h1>
      
      {/* Status */}
      <div style={{ 
        padding: '15px', 
        marginBottom: '20px', 
        borderRadius: '10px',
        background: isReady ? '#d4edda' : '#fff3cd'
      }}>
        {isLoading && (
          <div>
            <strong>Ładowanie modelu...</strong>
            {progress && (
              <div>
                {progress.file}: {progress.progress}%
              </div>
            )}
          </div>
        )}
        {isReady && <strong>Model ready</strong>}
        {providerError && (
          <div style={{ color: '#721c24' }}>
            Error: {providerError.message}
          </div>
        )}
      </div>

      {/* Messages */}
      <div style={{
        height: '400px',
        overflowY: 'auto',
        padding: '20px',
        background: '#f5f5f5',
        borderRadius: '10px',
        marginBottom: '20px',
      }}>
        {messages.map((msg, idx) => (
          <div
            key={idx}
            style={{
              display: 'flex',
              justifyContent: msg.role === 'user' ? 'flex-end' : 'flex-start',
              marginBottom: '10px',
            }}
          >
            <div
              style={{
                maxWidth: '70%',
                padding: '10px 15px',
                borderRadius: '15px',
                background: msg.role === 'user' ? '#667eea' : '#fff',
                color: msg.role === 'user' ? '#fff' : '#333',
                boxShadow: '0 2px 5px rgba(0,0,0,0.1)',
              }}
            >
              {msg.role === 'system' ? (
                <em>System: {msg.content}</em>
              ) : (
                msg.content
              )}
            </div>
          </div>
        ))}
        {isSending && (
          <div style={{ textAlign: 'center', color: '#666' }}>
            Generowanie odpowiedzi...
          </div>
        )}
      </div>

      {/* Input */}
      <div style={{ display: 'flex', gap: '10px' }}>
        <input
          type="text"
          value={input}
          onChange={(e) => setInput(e.target.value)}
          onKeyPress={handleKeyPress}
          placeholder="Napisz wiadomość..."
          disabled={!isReady || isSending}
          style={{
            flex: 1,
            padding: '12px',
            fontSize: '16px',
            border: '2px solid #e0e0e0',
            borderRadius: '10px',
          }}
        />
        <button
          onClick={handleSend}
          disabled={!isReady || isSending || !input.trim()}
          style={{
            padding: '12px 24px',
            fontSize: '16px',
            background: '#667eea',
            color: '#fff',
            border: 'none',
            borderRadius: '10px',
            cursor: !isReady || isSending ? 'not-allowed' : 'pointer',
            opacity: !isReady || isSending ? 0.6 : 1,
          }}
        >
          Wyślij
        </button>
        <button
          onClick={clear}
          disabled={messages.length === 0}
          style={{
            padding: '12px 24px',
            fontSize: '16px',
            background: '#6c757d',
            color: '#fff',
            border: 'none',
            borderRadius: '10px',
            cursor: messages.length === 0 ? 'not-allowed' : 'pointer',
            opacity: messages.length === 0 ? 0.6 : 1,
          }}
        >
          Wyczyść
        </button>
      </div>

      {chatError && (
        <div style={{ 
          marginTop: '10px', 
          padding: '10px', 
          background: '#f8d7da',
          color: '#721c24',
          borderRadius: '5px',
        }}>
          Błąd: {chatError.message}
        </div>
      )}
    </div>
  );
}

// Example usage in your app:
// import { ChatApp } from './examples/react-chat-example';
// 
// function App() {
//   return <ChatApp />;
// }
